### ISSUE TITLE
Allow selecting a specific suffix for email

### ISSUE THREAD

**Issue by Matanga1-2** [galezra/lusha-register-extension#13]
## Background
When registering with Lugister, I can select my email - 
![image](https://github.com/galezra/lusha-register-extension/assets/24847398/8b706535-855a-4ba1-83ef-44acdf8cdd56)
Then, while registering it adds a custom suffix -
![image](https://github.com/galezra/lusha-register-extension/assets/24847398/ea13b5af-7fef-4cac-8cb8-df1ee2ea7f1e)

## The problem
There are cases where I need a specific suffix, for example "p42".
Usually it's for testing purposes where the suffix means something.

## Workaround
As a workaround, I turn off the "auto-register" and add the suffix myself.

## Suggestion
I suggest an optional field to fill in the desired suffix (e.f., "p42").
Then, the logic to create the email would be
{{name}}+{{chose suffix}}{{custom suffix}}@{{domain}}

**Comment by galezra** [comment]
Hi Matan,

I understand the challenge you're facing with needing specific email suffixes for testing purposes. It's great that you've already thought of a workaround by manually adding the suffix.

Regarding your suggestion, it's indeed a practical approach. To implement this, you can modify the Lugister configuration to include an optional field for the custom suffix. Your idea of using the format {{name}}+{{chosen suffix}} is right on track. Once you set this up, Lugister will automatically generate the custom prefix followed by its auto-generated suffix, forming a complete email address like {{name}}+{{chosen suffix}}+{{auto custom suffix}}@{{domain}}.

This addition not only addresses your current needs but also adds flexibility to the email registration process, benefiting others who might have similar requirements.

Additionally, I want to extend a heartfelt thank you for bringing up this issue. This is the first issue reported for our repository, and your contribution is incredibly valuable to us. It's insights like yours that help us improve and make our tool more user-friendly.

If you need any further assistance or have more ideas, feel free to share!
